#!/usr/bin/env sh

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

export PATH="$HOME/.local/bin:$HOME/bin:$HOME/bin/youtube-dl:$PATH"
export EDITOR='vim'
export TERMINAL='urxvtc'
export BROWSER='firefox'
export READER='zathura'
export FILEMAN='mc'
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
export MOZ_DISABLE_PANGO=1
export SDL_AUDIODRIVER='pulse'

# less/man colors
export LESS=-R
#export LESS_TERMCAP_mb="$(printf '%b' '.[1;31m')"; a="${a%_}"
#export LESS_TERMCAP_md="$(printf '%b' '.[1;36m')"; a="${a%_}"
#export LESS_TERMCAP_me="$(printf '%b' '.[0m')"; a="${a%_}"
#export LESS_TERMCAP_so="$(printf '%b' '.[01;44;33m')"; a="${a%_}"
#export LESS_TERMCAP_se="$(printf '%b' '.[0m')"; a="${a%_}"
#export LESS_TERMCAP_us="$(printf '%b' '.[1;32m')"; a="${a%_}"
#export LESS_TERMCAP_ue="$(printf '%b' '.[0m')"; a="${a%_}"

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# gPodder settings
export GPODDER_HOME=$HOME/.gPodder
export GPODDER_DOWNLOAD_DIR=$HOME/download/podcast

# quick cd to underlying dirs
export CDPATH=:..:~:~/work/dev:~/work/projects

