#!/usr/bin/env sh

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# source from https://unix.stackexchange.com/questions/14895/duplicate-entries-in-path-a-problem
pathadd() {
    [ ! -d "$1" ] && return 0
    case ":$PATH:" in
        *":$1:"*) :;; # already there
        *) PATH="$1:$PATH";; # or PATH="$PATH:$1"
    esac
}

pathadd "$HOME/.local/bin"
pathadd "$HOME/bin"
export EDITOR='vim'
export TERMINAL='urxvtc'
export BROWSER='firefox'
export READER='zathura'
export FILEMAN='pcmanfm'
export TASKMAN='xfce4-taskmanager'
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
#export MOZ_DISABLE_PANGO=1
export SDL_AUDIODRIVER='pulse'

export LESS=-R

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# gPodder settings
export GPODDER_HOME=$HOME/.gPodder
export GPODDER_DOWNLOAD_DIR=$HOME/download/podcast

# quick cd to underlying dirs
export CDPATH=:..:~:~/work/dev:~/work/projects

unset pathadd
